version: "3.9"

services:
  #front-end:
  #  build:
  #    context: ./../../Streetcode/Streetcode.Client
  #    dockerfile: Dockerfile
  #  init: true
  #  restart: always
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    back-end:
  # condition: service_healthy
  
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000/tcp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 15s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5000"
    volumes:
      - "./healthchecks:/healthchecks"
    labels:       
      atom: ${DOCKER_ATOM:-Streetcode}
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "$$SA_PASSWORD", "-Q", "select 1", " -b", "-o /dev/null"]
      interval: 3s
      retries: 20
    volumes:
      - db-data:/var/lib/mssql/data
      - "./healthchecks:/healthchecks"
    ports:
      - "${MS_SQL_DB_PORT}:1433"
    labels:       
      atom: ${DOCKER_ATOM:-Streetcode}
        
volumes:
  db-data:
    labels:
      atom: ${DOCKER_ATOM:-Streetcode}