// <auto-generated />
using System;
using EFTask.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFTask.Migrations
{
    [DbContext(typeof(StreetcodeDbContext))]
    [Migration("20221212181852_Change Seeding Id")]
    partial class ChangeSeedingId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArtStreetcode", b =>
                {
                    b.Property<int>("ArtsId")
                        .HasColumnType("int");

                    b.Property<int>("StreetcodesId")
                        .HasColumnType("int");

                    b.HasKey("ArtsId", "StreetcodesId");

                    b.HasIndex("StreetcodesId");

                    b.ToTable("streetcode_arts", "streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.AdditionalContent.Coordinates.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Longtitude")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("coordinate_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("coordinates", "add_content");

                    b.HasDiscriminator<string>("coordinate_type").HasValue("coordinate_base");
                });

            modelBuilder.Entity("EFTask.Entities.AdditionalContent.Subtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("StreetcodeId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreetcodeId");

                    b.ToTable("subtitles", "add_content");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "description",
                            FirstName = "Dmytro",
                            LastName = "Buchkovsky",
                            Status = (byte)0,
                            StreetcodeId = 1,
                            Url = "https://t.me/MaisterD"
                        },
                        new
                        {
                            Id = 2,
                            Description = "description",
                            FirstName = "Dmytro",
                            LastName = "Buchkovsky",
                            Status = (byte)1,
                            StreetcodeId = 2,
                            Url = "https://t.me/MaisterD"
                        },
                        new
                        {
                            Id = 3,
                            Description = "description",
                            FirstName = "Dmytro",
                            LastName = "Buchkovsky",
                            Status = (byte)0,
                            StreetcodeId = 3,
                            Url = "https://t.me/MaisterD"
                        },
                        new
                        {
                            Id = 4,
                            Description = "description",
                            FirstName = "Oleksndr",
                            LastName = "Lazarenko",
                            Status = (byte)0,
                            StreetcodeId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Oleksndr",
                            LastName = "Lazarenko",
                            Status = (byte)0,
                            StreetcodeId = 2
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Yaroslav",
                            LastName = "Chushenko",
                            Status = (byte)1,
                            StreetcodeId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Yaroslav",
                            LastName = "Chushenko",
                            Status = (byte)1,
                            StreetcodeId = 3
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Nazarii",
                            LastName = "Hovdysh",
                            Status = (byte)0,
                            StreetcodeId = 4
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Tatiana",
                            LastName = "Shumylo",
                            Status = (byte)1,
                            StreetcodeId = 4
                        });
                });

            modelBuilder.Entity("EFTask.Entities.AdditionalContent.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tags", "add_content");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "writer"
                        },
                        new
                        {
                            Id = 2,
                            Title = "artist"
                        },
                        new
                        {
                            Id = 3,
                            Title = "composer"
                        },
                        new
                        {
                            Id = 4,
                            Title = "wictory"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Feedback.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("responses", "feedback");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Good Job",
                            Email = "dmytrobuchkovsky@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nice project",
                            Email = "mail@gmail.com",
                            FirstName = "Dmytro"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Media.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetcodeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StreetcodeId")
                        .IsUnique();

                    b.ToTable("audios", "media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "for streetcode1",
                            StreetcodeId = 1,
                            Title = "audio1",
                            Url = "https://somelink1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "for streetcode2",
                            StreetcodeId = 2,
                            Title = "audio2",
                            Url = "https://somelink2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "for streetcode3",
                            StreetcodeId = 3,
                            Title = "audio3",
                            Url = "https://somelink3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "for streetcode4",
                            StreetcodeId = 4,
                            Title = "audio4",
                            Url = "https://somelink4"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Media.Images.Art", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("arts", "media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "«Погруддя жінки» — портрет роботи Тараса Шевченка (копія з невідомого оригіналу) виконаний ним у Вільно в 1830 році на папері італійським олівцем. Розмір 47,5 × 38. Зустрічається також під назвою «Жіноча голівка»",
                            ImageId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "«Погруддя жінки» — портрет роботи Тараса Шевченка (копія з невідомого оригіналу) виконаний ним у Вільно в 1830 році на папері італійським олівцем. Розмір 47,5 × 38. Зустрічається також під назвою «Жіноча голівка»",
                            ImageId = 3
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 4
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Media.Images.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("images", "media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alt = "Портрет Тараса Шевченка",
                            Title = "Тарас Шевченко",
                            Url = "https://www.bing.com/images/search?view=detailV2&ccid=07Ymnt6l&id=A8ACFBEB6A3695B1E7DD2887A46505D759921BDC&thid=OIP.07Ymnt6ljB86Jx-Fy2wGUwHaKY&mediaurl=https%3A%2F%2Fproprikol.ru%2Fwp-content%2Fuploads%2F2021%2F05%2Fkartinki-taras-shevchenko-39.jpg&cdnurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.d3b6269edea58c1f3a271f85cb6c0653%3Frik%3D3BuSWdcFZaSHKA%26pid%3DImgRaw%26r%3D0&exph=1581&expw=1128&q=%d1%82%d0%b0%d1%80%d0%b0%d1%81+%d1%88%d0%b5%d0%b2%d1%87%d0%b5%d0%bd%d0%ba%d0%be&simid=608002717784548528&form=IRPRST&ck=0EF4CC2DA9612AC10DAE96953F62051F&selectedindex=1&ajaxhist=0&ajaxserp=0&vt=0&sim=11"
                        },
                        new
                        {
                            Id = 2,
                            Alt = "Тарас Шевченко: Погруддя жінки",
                            Title = "Погруддя жінки",
                            Url = "https://upload.wikimedia.org/wikipedia/commons/1/10/Taras_Shevchenko_painting_0001.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Alt = "Тарас Шевченко: Портрет Павла Васильовича Енгельгардта",
                            Title = "Портрет Павла Васильовича Енгельгардта",
                            Url = "https://uk.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD_%D1%96_%D0%BC%D0%B0%D0%BB%D1%8E%D0%BD%D0%BA%D1%96%D0%B2_%D0%A2%D0%B0%D1%80%D0%B0%D1%81%D0%B0_%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%B0#/media/%D0%A4%D0%B0%D0%B9%D0%BB:Enhelhard_by_Shevchenko.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Alt = "Тарас Шевченко: Портрет невідомого",
                            Title = "Портрет невідомого",
                            Url = "https://uk.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD_%D1%96_%D0%BC%D0%B0%D0%BB%D1%8E%D0%BD%D0%BA%D1%96%D0%B2_%D0%A2%D0%B0%D1%80%D0%B0%D1%81%D0%B0_%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%B0#/media/%D0%A4%D0%B0%D0%B9%D0%BB:Portret_nevidomoho_Shevchenko_.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Alt = "Кобзар",
                            Title = "Кобзар",
                            Url = "https://www.bing.com/images/search?view=detailV2&ccid=6juPycgD&id=00A2C7B1F325A9870421D651A956BCE2C851654E&thid=OIP.6juPycgDNwJ3v2Zr-kde1gHaK_&mediaurl=https%3A%2F%2Fwww.megakniga.com.ua%2Fuploads%2Fcache%2FProducts%2FProduct_images_343456%2Fd067b1_w1600.jpg&cdnurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.ea3b8fc9c803370277bf666bfa475ed6%3Frik%3DTmVRyOK8VqlR1g%26pid%3DImgRaw%26r%3D0&exph=1200&expw=809&q=%d0%ba%d0%be%d0%b1%d0%b7%d0%b0%d1%80&simid=608047540067197142&form=IRPRST&ck=4280C365AEBC65D796FBF885B3252710&selectedindex=1&ajaxhist=0&ajaxserp=0&vt=0&sim=11"
                        },
                        new
                        {
                            Id = 6,
                            Alt = "Мико́ла Костома́ров",
                            Title = "Мико́ла Костома́ров",
                            Url = "https://www.bing.com/images/search?view=detailV2&ccid=KUJZwRaU&id=A53DDEBFF57BE2396FB7FA50737F83704B1BE30F&thid=OIP.KUJZwRaUjipKMLR8H91BrAAAAA&mediaurl=https%3a%2f%2fgdb.rferl.org%2f224F2B76-EE74-4B85-A78A-BF8A354FA0B1_w250_r0_s.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.294259c116948e2a4a30b47c1fdd41ac%3frik%3dD%252bMbS3CDf3NQ%252bg%26pid%3dImgRaw%26r%3d0&exph=340&expw=250&q=%d0%9c%d0%b8%d0%ba%d0%be%cc%81%d0%bb%d0%b0+%d0%9a%d0%be%d1%81%d1%82%d0%be%d0%bc%d0%b0%cc%81%d1%80%d0%be%d0%b2&simid=608030609289524022&FORM=IRPRST&ck=E08972A7A7E2CEE9B67158DDC372F92F&selectedIndex=3&ajaxhist=0&ajaxserp=0"
                        },
                        new
                        {
                            Id = 7,
                            Alt = "Василь Білозерський",
                            Title = "Василь Білозерський",
                            Url = "https://www.bing.com/images/search?view=detailV2&ccid=hIQUFjAM&id=B14676F51B4A0EB314ED15283540D088B3030E28&thid=OIP.hIQUFjAMGwOt7f7ujR44aQAAAA&mediaurl=https%3a%2f%2fnaurok-test.nyc3.cdn.digitaloceanspaces.com%2fuploads%2ftest%2f229691%2f36505%2f276576_1582512990.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.84841416300c1b03adedfeee8d1e3869%3frik%3dKA4Ds4jQQDUoFQ%26pid%3dImgRaw%26r%3d0&exph=351&expw=240&q=%d0%92%d0%b0%d1%81%d0%b8%d0%bb%d1%8c+%d0%91%d1%96%d0%bb%d0%be%d0%b7%d0%b5%d1%80%d1%81%d1%8c%d0%ba%d0%b8%d0%b9&simid=608001205960330039&FORM=IRPRST&ck=07DE282212732F4C0712D614C87002F3&selectedIndex=1&ajaxhist=0&ajaxserp=0"
                        },
                        new
                        {
                            Id = 8,
                            Alt = "Звільнення Херсона",
                            Title = "Звільнення Херсона",
                            Url = "https://www.bing.com/images/search?view=detailV2&ccid=F5o3vrW9&id=5409686EF1396243251CE5AF505766A0A2D0662E&thid=OIP.F5o3vrW9jZJ9ECMgkmevTwHaFj&mediaurl=https%3a%2f%2fstorage1.censor.net%2fimages%2f1%2f7%2f9%2fa%2f179a37beb5bd8d927d1023209267af4f%2foriginal.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.179a37beb5bd8d927d1023209267af4f%3frik%3dLmbQoqBmV1Cv5Q%26pid%3dImgRaw%26r%3d0&exph=720&expw=960&q=%d0%b2%d0%b8%d0%b7%d0%b2%d0%be%d0%bb%d0%b5%d0%bd%d0%bd%d1%8f+%d1%85%d0%b5%d1%80%d1%81%d0%be%d0%bd%d1%83&simid=608050323200235844&FORM=IRPRST&ck=C9A86B9D5EBBADF456F315DFD0BA990B&selectedIndex=3&ajaxhist=0&ajaxserp=0"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Media.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetcodeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StreetcodeId");

                    b.ToTable("videos", "media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "for streetcode1",
                            StreetcodeId = 2,
                            Title = "audio1",
                            Url = "https://somelink1"
                        },
                        new
                        {
                            Id = 2,
                            StreetcodeId = 1,
                            Title = "Біографія Т.Г.Шевченка",
                            Url = "https://www.youtube.com/watch?v=VVFEi6lTpZk&ab_channel=%D0%9E%D1%81%D1%82%D0%B0%D0%BD%D0%BD%D1%96%D0%B9%D0%93%D0%B5%D1%82%D1%8C%D0%BC%D0%B0%D0%BD"
                        },
                        new
                        {
                            Id = 3,
                            Description = "За виконанням Богдана Ступки",
                            StreetcodeId = 1,
                            Title = "Вірш: Мені Однаково",
                            Url = "https://www.youtube.com/watch?v=f55dHPEY-0U&ab_channel=%D0%86%D0%B3%D0%BE%D1%80%D0%9E%D0%BF%D0%B0%D1%86%D1%8C%D0%BA%D0%B8%D0%B9"
                        },
                        new
                        {
                            Id = 4,
                            Description = "За виконанням Богдана Ступки",
                            StreetcodeId = 4,
                            Title = "Вірш: Мені Однаково",
                            Url = "https://youtu.be/v3siIQi4nCQ"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Partners.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("partners", "partner_sponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Developers",
                            LogoUrl = "https://www.bing.com/images/search?view=detailV2&ccid=g3DnkGqg&id=98C6F1FDD6CDA685A3DE2AD392FAC228180A28CC&thid=OIP.g3DnkGqgmhKFWM2ct5mXrAHaHa&mediaurl=https%3a%2f%2fyt3.ggpht.com%2fa-%2fAN66SAxaiWXvFxW9BUQ32pzQ5tv5UuXz2fLZ20LaMg%3ds900-mo-c-c0xffffffff-rj-k-no&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.8370e7906aa09a128558cd9cb79997ac%3frik%3dzCgKGCjC%252bpLTKg%26pid%3dImgRaw%26r%3d0&exph=900&expw=900&q=softserve&simid=608013145967840441&FORM=IRPRST&ck=C08BED6E397D35D8A4824BB4B78EBCE8&selectedIndex=1&ajaxhist=0&ajaxserp=0",
                            TargetUrl = "https://www.softserveinc.com/en-us",
                            Title = "SoftServe"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "https://www.bing.com/images/search?view=detailV2&ccid=9TObzn%2ba&id=21D8755FE7846CE9660BC2365F5EE70417D31DA7&thid=OIP.9TObzn-a15MsLhdfHh1e_gHaE8&mediaurl=https%3a%2f%2fi2.wp.com%2feuropeangaming.eu%2fportal%2fwp-content%2fuploads%2f2020%2f02%2f5-10.jpg%3ffit%3d1200%252C800%26ssl%3d1&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.f5339bce7f9ad7932c2e175f1e1d5efe%3frik%3dpx3TFwTnXl82wg%26pid%3dImgRaw%26r%3d0&exph=800&expw=1200&q=parimatch&simid=607987165708116105&FORM=IRPRST&ck=BA1164F39CC2BBD1CE20F50A93602E5C&selectedIndex=1&ajaxhist=0&ajaxserp=0",
                            TargetUrl = "https://parimatch.com/",
                            Title = "parimatch"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "https://www.bing.com/images/search?view=detailV2&ccid=9TObzn%2ba&id=21D8755FE7846CE9660BC2365F5EE70417D31DA7&thid=OIP.9TObzn-a15MsLhdfHh1e_gHaE8&mediaurl=https%3a%2f%2fi2.wp.com%2feuropeangaming.eu%2fportal%2fwp-content%2fuploads%2f2020%2f02%2f5-10.jpg%3ffit%3d1200%252C800%26ssl%3d1&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.f5339bce7f9ad7932c2e175f1e1d5efe%3frik%3dpx3TFwTnXl82wg%26pid%3dImgRaw%26r%3d0&exph=800&expw=1200&q=parimatch&simid=607987165708116105&FORM=IRPRST&ck=BA1164F39CC2BBD1CE20F50A93602E5C&selectedIndex=1&ajaxhist=0&ajaxserp=0",
                            TargetUrl = "https://parimatch.com/",
                            Title = "comunity partner"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Partners.PartnerSourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("partner_source_links", "partner_sponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "",
                            PartnerId = 1,
                            TargetUrl = "https://www.linkedin.com/company/softserve/",
                            Title = "LinkedIn"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "",
                            PartnerId = 1,
                            TargetUrl = "https://www.instagram.com/softserve_people/",
                            Title = "Instagram"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "",
                            PartnerId = 1,
                            TargetUrl = "https://www.facebook.com/SoftServeCompany",
                            Title = "facebook"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Partners.StreetcodePartner", b =>
                {
                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("StreetcodeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSponsor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("PartnerId", "StreetcodeId");

                    b.HasIndex("StreetcodeId");

                    b.ToTable("streetcode_partners", "partner_sponsors");

                    b.HasData(
                        new
                        {
                            PartnerId = 1,
                            StreetcodeId = 1,
                            IsSponsor = true
                        },
                        new
                        {
                            PartnerId = 1,
                            StreetcodeId = 2,
                            IsSponsor = true
                        },
                        new
                        {
                            PartnerId = 1,
                            StreetcodeId = 3,
                            IsSponsor = false
                        },
                        new
                        {
                            PartnerId = 2,
                            StreetcodeId = 1,
                            IsSponsor = true
                        },
                        new
                        {
                            PartnerId = 2,
                            StreetcodeId = 2,
                            IsSponsor = false
                        },
                        new
                        {
                            PartnerId = 3,
                            StreetcodeId = 3,
                            IsSponsor = false
                        },
                        new
                        {
                            PartnerId = 1,
                            StreetcodeId = 4,
                            IsSponsor = true
                        },
                        new
                        {
                            PartnerId = 2,
                            StreetcodeId = 4,
                            IsSponsor = true
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Sources.SourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("StreetcodeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StreetcodeId");

                    b.ToTable("source_links", "sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StreetcodeId = 1,
                            Title = "Вікіпедія",
                            Url = "https://uk.wikipedia.org/wiki/%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%BE_%D0%A2%D0%B0%D1%80%D0%B0%D1%81_%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D0%BE%D0%B2%D0%B8%D1%87"
                        },
                        new
                        {
                            Id = 2,
                            StreetcodeId = 1,
                            Title = "Кобзар",
                            Url = "https://uk.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:%D0%A2%D0%B0%D1%80%D0%B0%D1%81_%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%BE._%D0%9A%D0%BE%D0%B1%D0%B7%D0%B0%D1%80._1840.pdf"
                        },
                        new
                        {
                            Id = 3,
                            StreetcodeId = 4,
                            Title = "Св'яткування звільнення",
                            Url = "https://tsn.ua/ukrayina/z-pisnyami-i-tostami-zvilnennya-hersona-svyatkuyut-v-inshih-mistah-ukrayini-i-navit-za-kordonom-video-2200096.html"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Sources.SourceLinkCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("source_link_categories", "sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "book"
                        },
                        new
                        {
                            Id = 2,
                            Title = "video"
                        },
                        new
                        {
                            Id = 3,
                            Title = "article"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.RelatedFigure", b =>
                {
                    b.Property<int>("ObserverId")
                        .HasColumnType("int");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("ObserverId", "TargetId");

                    b.HasIndex("TargetId");

                    b.ToTable("related_figures", "streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.Streetcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EventEndOrPersonDeathDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventStartOrPersonBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Teaser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("streetcode_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("streetcodes", "streetcode");

                    b.HasDiscriminator<string>("streetcode_type").HasValue("streetcode_base");
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.TextContent.Fact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FactContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("facts", "streetcode");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FactContent = "Навесні 1838-го Карл Брюллов і Василь Жуковський вирішили викупити молодого поета з кріпацтва. Енгельгардт погодився відпустити кріпака за великі гроші — 2500 рублів. Щоб здобути такі гроші, Карл Брюллов намалював портрет Василя Жуковського — вихователя спадкоємця престолу Олександра Миколайовича, і портрет розіграли в лотереї, у якій взяла участь імператорська родина. Лотерея відбулася 4 травня 1838 року, а 7 травня Шевченкові видали відпускну.",
                            Title = "Викуп з кріпацтва"
                        },
                        new
                        {
                            Id = 2,
                            FactContent = " Ознайомившись випадково з рукописними творами Шевченка й вражений ними, П. Мартос виявив до них великий інтерес. Він порадився із Є. Гребінкою і запропонував Шевченку видати їх окремою книжкою, яку згодом назвали «Кобзарем».",
                            ImageId = 5,
                            Title = "Перший Кобзар"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.TextContent.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("terms", "streetcode");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Етнографія — суспільствознавча наука, об'єктом дослідження якої є народи, їхня культура і побут, походження, розселення, процеси культурно-побутових відносин на всіх етапах історії людства.",
                            Title = "етнограф"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Гра́фіка — вид образотворчого мистецтва, для якого характерна перевага ліній і штрихів, використання контрастів білого та чорного та менше, ніж у живописі, використання кольору. Твори можуть мати як монохромну, так і поліхромну гаму.",
                            Title = "гравер"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Кріпа́цтво, або кріпосне́ право, у вузькому сенсі — правова система, або система правових норм при феодалізмі, яка встановлювала залежність селянина від феодала й неповну власність феодала на селянина.",
                            Title = "кріпак"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.TextContent.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("StreetcodeId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StreetcodeId")
                        .IsUnique();

                    b.ToTable("texts", "streetcode");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StreetcodeId = 1,
                            TextContent = "Тарас Шевченко народився 9 березня 1814 року в селі Моринці Пединівської волості Звенигородського повіту Київської губернії. Був третьою дитиною селян-кріпаків Григорія Івановича Шевченка та Катерини Якимівни після сестри Катерини (1804 — близько 1848) та брата Микити (1811 — близько 1870).\r\n\r\nЗа родинними переказами, Тарасові діди й прадіди з батьківського боку походили від козака Андрія, який на початку XVIII століття прийшов із Запорізької Січі. Батьки його матері, Катерини Якимівни Бойко, були переселенцями з Прикарпаття.\r\n\r\n1816 року сім'я Шевченків переїхала до села Кирилівка Звенигородського повіту, звідки походив Григорій Іванович. Дитячі роки Тараса пройшли в цьому селі. 1816 року народилася Тарасова сестра Ярина, 1819 року — сестра Марія, а 1821 року народився Тарасів брат Йосип.\r\n\r\nВосени 1822 року Тарас Шевченко почав учитися грамоти у дяка Совгиря. Тоді ж ознайомився з творами Григорія Сковороди.\r\n\r\n10 лютого 1823 року його старша сестра Катерина вийшла заміж за Антона Красицького — селянина із Зеленої Діброви, а 1 вересня 1823 року від тяжкої праці й злиднів померла мати Катерина. \r\n\r\n19 жовтня 1823 року батько одружився вдруге з удовою Оксаною Терещенко, в якої вже було троє дітей. Вона жорстоко поводилася з нерідними дітьми, зокрема з малим Тарасом. 1824 року народилася Тарасова сестра Марія — від другого батькового шлюбу.",
                            Title = "Дитинство та юність"
                        },
                        new
                        {
                            Id = 2,
                            StreetcodeId = 2,
                            TextContent = "Батьки М. І. Костомарова намагалися прищепити сину вільнолюбні ідеї і дати добру освіту. Тому вже з 10 років М. Костомарова відправили навчатися до Московського пансіону, а згодом до Воронезької гімназії, яку той закінчив 1833 р.\r\n\r\n1833 р. М. І. Костомаров вступає на історико-філологічний факультет Харківського університету. Вже у цьому навчальному закладі він проявив непересічні здібності до навчання.\r\n\r\nВ університеті Микола Костомаров вивчав стародавні й нові мови, цікавився античною історією, німецькою філософією і новою французькою літературою, учився грати на фортепіано, пробував писати вірші. Зближення з гуртком українських романтиків Харківського університету незабаром визначило його захоплення переважно фольклором і козацьким минулим України.\r\n\r\nУ ті роки у Харківському університеті навколо професора-славіста і літератора-романтика І. Срезневського сформувався гурток студентів, захоплених збиранням зразків української народної пісенної творчості. Вони сприймали фольклор як вираження народного духу, самі складали вірші, балади і ліричні пісні, звертаючись до народної творчості.\r\n\r\nКостомаров в університетські роки дуже багато читав. Перевантаження позначилося на його здоров'ї — ще за студентства значно погіршився зір.\r\n\r\nНа світогляд М. І. Костомарова вплинули професор грецької літератури Харківського університету А. О. Валицький та професор всесвітньої історії М. М. Лунін.\r\n\r\n1836 р. М. І. Костомаров закінчив університет, а в січні 1837 р. склав іспити на ступінь кандидата й отримав направлення у Кінбурнський 7-й драгунський полк юнкером.\r\n\r\nУ січні 1837 року Костомаров склав іспити з усіх предметів, і 8 грудня 1837 року його затвердили в статусі кандидата.",
                            Title = "Юність і навчання"
                        },
                        new
                        {
                            Id = 3,
                            StreetcodeId = 3,
                            TextContent = "Народився у дворянській родині на хуторі Мотронівка (нині у межах с. Оленівка поблизу Борзни).\r\n\r\nУ 1843–1846 роках здобув вищу освіту на історико-філологічному факультеті Київського Імператорського університету св. Володимира.\r\n\r\n1846–1847 — учитель Петровського кадетського корпусу у Полтаві.\r\n\r\nРазом з М. Костомаровим і М. Гулаком був організатором Кирило-Мефодіївського братства. Брав участь у створенні «Статуту Слов'янського братства св. Кирила і Мефодія». Автор «Записки» — пояснень до статуту братства. Розвивав ідеї християнського соціалізму, виступав за об'єднання всіх слов'янських народів у республіканську федерацію, в якій провідну роль відводив Україні.\r\n1847 — 10 квітня був заарештований у Варшаві. Засланий до Олонецької губернії під нагляд поліції. Служив у Петрозаводському губернському правлінні.\r\n\r\n1856 — звільнений із заслання. Оселився у Санкт-Петербурзі, де став активним членом місцевого гуртка українців.\r\n\r\n1861–1862 — редактор першого українського щомісячного журналу «Основа».\r\n\r\nЗгодом служив у Варшаві. Підтримував зв'язки з Галичиною, співпрацював у часописах «Мета» і «Правда».\r\n\r\nОстанні роки життя провів на хуторі Мотронівці.",
                            Title = "Життєпис"
                        },
                        new
                        {
                            Id = 4,
                            StreetcodeId = 4,
                            TextContent = "Експерти пояснили, що дасть херсонська перемога українським силам\r\n\r\nНа тлі заяв окупантів про відведення військ та сил рф від Херсона та просування ЗСУ на херсонському напрямку українські бійці можуть отримати вогневий контроль над найважливішими дорогами Криму. Більше того, звільнення облцентру переріже постачання зброї для росії.",
                            Title = "визволення Херсона"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Timeline.HistoricalContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("historical_contexts", "timeline");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Book"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Wideo"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Article"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Timeline.TimelineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("timeline_items", "timeline");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(1831, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Переїхавши 1831 року з Вільна до Петербурга, поміщик П. Енгельгардт узяв із собою Шевченка, а щоб згодом мати зиск на художніх творах власного «покоєвого художника», підписав контракт й віддав його в науку на чотири роки до живописця В. Ширяєва, у якого й замешкав Тарас до 1838 року.",
                            Title = "Перші роки в Петербурзі"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(1830, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Засвідчивши свою відпускну в петербурзькій Палаті цивільного суду, Шевченко став учнем Академії мистецтв, де його наставником став К. Брюллов. За словами Шевченка: «настала найсвітліша доба його життя, незабутні, золоті дні» навчання в Академії мистецтв, яким він присвятив у 1856 році автобіографічну повість «Художник».",
                            Title = "Учень Петербурзької академії мистецтв"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Toponyms.Toponym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("toponyms", "toponyms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "вулиця Шевченка"
                        },
                        new
                        {
                            Id = 2,
                            Title = "парк Шевченка"
                        },
                        new
                        {
                            Id = 3,
                            Title = "місто Херсон"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Transactions.TransactionLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("QrCodeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetcodeId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StreetcodeId")
                        .IsUnique();

                    b.ToTable("transaction_links", "transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QrCodeUrl = "https://qrcode/1",
                            StreetcodeId = 1,
                            Url = "https://streetcode/1"
                        },
                        new
                        {
                            Id = 2,
                            QrCodeUrl = "https://qrcode/2",
                            StreetcodeId = 2,
                            Url = "https://streetcode/2"
                        },
                        new
                        {
                            Id = 3,
                            QrCodeUrl = "https://qrcode/3",
                            StreetcodeId = 3,
                            Url = "https://streetcode/3"
                        },
                        new
                        {
                            Id = 4,
                            QrCodeUrl = "https://qrcode/4",
                            StreetcodeId = 4,
                            Url = "https://streetcode/4"
                        });
                });

            modelBuilder.Entity("FactStreetcode", b =>
                {
                    b.Property<int>("FactsId")
                        .HasColumnType("int");

                    b.Property<int>("StreetcodesId")
                        .HasColumnType("int");

                    b.HasKey("FactsId", "StreetcodesId");

                    b.HasIndex("StreetcodesId");

                    b.ToTable("streetcode_fact", "streetcode");
                });

            modelBuilder.Entity("HistoricalContextTimelineItem", b =>
                {
                    b.Property<int>("HistoricalContextsId")
                        .HasColumnType("int");

                    b.Property<int>("TimelineItemsId")
                        .HasColumnType("int");

                    b.HasKey("HistoricalContextsId", "TimelineItemsId");

                    b.HasIndex("TimelineItemsId");

                    b.ToTable("timeline_item_historical_context", "timeline");
                });

            modelBuilder.Entity("ImageStreetcode", b =>
                {
                    b.Property<int>("ImagesId")
                        .HasColumnType("int");

                    b.Property<int>("StreetcodesId")
                        .HasColumnType("int");

                    b.HasKey("ImagesId", "StreetcodesId");

                    b.HasIndex("StreetcodesId");

                    b.ToTable("streetcode_image", "streetcode");
                });

            modelBuilder.Entity("SourceLinkSourceLinkCategory", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("SourceLinksId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "SourceLinksId");

                    b.HasIndex("SourceLinksId");

                    b.ToTable("SourceLinkSourceLinkCategory", "sources");
                });

            modelBuilder.Entity("StreetcodeTag", b =>
                {
                    b.Property<int>("StreetcodesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("StreetcodesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("streetcode_tag", "streetcode");
                });

            modelBuilder.Entity("StreetcodeTimelineItem", b =>
                {
                    b.Property<int>("StreetcodesId")
                        .HasColumnType("int");

                    b.Property<int>("TimelineItemsId")
                        .HasColumnType("int");

                    b.HasKey("StreetcodesId", "TimelineItemsId");

                    b.HasIndex("TimelineItemsId");

                    b.ToTable("streetcode_timeline_item", "streetcode");
                });

            modelBuilder.Entity("StreetcodeToponym", b =>
                {
                    b.Property<int>("StreetcodesId")
                        .HasColumnType("int");

                    b.Property<int>("ToponymsId")
                        .HasColumnType("int");

                    b.HasKey("StreetcodesId", "ToponymsId");

                    b.HasIndex("ToponymsId");

                    b.ToTable("streetcode_toponym", "streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.AdditionalContent.Coordinates.StreetcodeCoordinate", b =>
                {
                    b.HasBaseType("EFTask.Entities.AdditionalContent.Coordinates.Coordinate");

                    b.Property<int>("StreetcodeId")
                        .HasColumnType("int");

                    b.HasIndex("StreetcodeId")
                        .IsUnique()
                        .HasFilter("[StreetcodeId] IS NOT NULL");

                    b.ToTable("coordinates", "add_content");

                    b.HasDiscriminator().HasValue("coordinate_streetcode");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Latitude = 49.8429m,
                            Longtitude = 24.0311m,
                            StreetcodeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 50.4550m,
                            Longtitude = 30.5238m,
                            StreetcodeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 50.4690m,
                            Longtitude = 30.5328m,
                            StreetcodeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 46.3950m,
                            Longtitude = 32.3738m,
                            StreetcodeId = 4
                        });
                });

            modelBuilder.Entity("EFTask.Entities.AdditionalContent.Coordinates.ToponymCoordinate", b =>
                {
                    b.HasBaseType("EFTask.Entities.AdditionalContent.Coordinates.Coordinate");

                    b.Property<int>("ToponymId")
                        .HasColumnType("int");

                    b.HasIndex("ToponymId");

                    b.ToTable("coordinates", "add_content");

                    b.HasDiscriminator().HasValue("coordinate_toponym");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 49.8429m,
                            Longtitude = 24.0311m,
                            ToponymId = 1
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 50.4500m,
                            Longtitude = 30.5233m,
                            ToponymId = 1
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 47.5m,
                            Longtitude = 37.32m,
                            ToponymId = 1
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 50.4600m,
                            Longtitude = 30.5243m,
                            ToponymId = 2
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 50.4550m,
                            Longtitude = 30.5238m,
                            ToponymId = 2
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 46.3950m,
                            Longtitude = 32.3738m,
                            ToponymId = 3
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.Types.EventStreetcode", b =>
                {
                    b.HasBaseType("EFTask.Entities.Streetcode.Streetcode");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("streetcodes", "streetcode");

                    b.HasDiscriminator().HasValue("streetcode_event");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2022, 12, 12, 20, 18, 50, 642, DateTimeKind.Local).AddTicks(7816),
                            EventEndOrPersonDeathDate = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventStartOrPersonBirthDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 4,
                            Teaser = "Звільнення Херсона (11 листопада 2022) — відвоювання Збройними силами України (ЗСУ) міста Херсона та інших районів Херсонської області та частини Миколаївської області на правому березі Дніпра, тоді як збройні сили РФ Сили відійшли на лівий берег (відомий як відхід росіян з Херсона, 9–11 листопада 2022 р.).",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1000,
                            Title = "Звільнення Херсона"
                        });
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.Types.PersonStreetcode", b =>
                {
                    b.HasBaseType("EFTask.Entities.Streetcode.Streetcode");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("streetcodes", "streetcode");

                    b.HasDiscriminator().HasValue("streetcode_person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 12, 12, 20, 18, 50, 642, DateTimeKind.Local).AddTicks(7668),
                            EventEndOrPersonDeathDate = new DateTime(1861, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventStartOrPersonBirthDate = new DateTime(1814, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 1,
                            Teaser = "Тара́с Григо́рович Шевче́нко (25 лютого (9 березня) 1814, с. Моринці, Київська губернія, Російська імперія (нині Звенигородський район, Черкаська область, Україна) — 26 лютого (10 березня) 1861, Санкт-Петербург, Російська імперія) — український поет, прозаїк, мислитель, живописець, гравер, етнограф, громадський діяч. Національний герой і символ України. Діяч українського національного руху, член Кирило-Мефодіївського братства. Академік Імператорської академії мистецтв",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 0,
                            FirstName = "Тарас",
                            LastName = "Шевченко",
                            MiddleName = "Григорович"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 12, 12, 20, 18, 50, 642, DateTimeKind.Local).AddTicks(7767),
                            EventEndOrPersonDeathDate = new DateTime(1885, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventStartOrPersonBirthDate = new DateTime(1817, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 2,
                            Teaser = "Мико́ла Іва́нович Костома́ров (4 (16) травня 1817, с. Юрасівка, Острогозький повіт, Воронезька губернія — 7 (19) квітня 1885, Петербург) — видатний український[8][9][10][11][12] історик, етнограф, прозаїк, поет-романтик, мислитель, громадський діяч, етнопсихолог[13][14][15]. \r\n\r\nБув співзасновником та активним учасником слов'янофільсько-українського київського об'єднання «Кирило - Мефодіївське братство». У 1847 році за участь в українофільському братстві Костомарова арештовують та перевозять з Києва до Петербурга,де він і провів решту свого життя.",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 0,
                            FirstName = "Мико́ла",
                            LastName = "Костома́ров",
                            MiddleName = "Іва́нович"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 12, 12, 20, 18, 50, 642, DateTimeKind.Local).AddTicks(7774),
                            EventEndOrPersonDeathDate = new DateTime(1899, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventStartOrPersonBirthDate = new DateTime(1825, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = 3,
                            Teaser = "Білозерський Василь Михайлович (1825, хутір Мотронівка, Чернігівщина — 20 лютого (4 березня) 1899) — український громадсько-політичний і культурний діяч, журналіст.",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 0,
                            FirstName = "Василь",
                            LastName = "Білозерський",
                            MiddleName = "Михайлович"
                        });
                });

            modelBuilder.Entity("ArtStreetcode", b =>
                {
                    b.HasOne("EFTask.Entities.Media.Images.Art", null)
                        .WithMany()
                        .HasForeignKey("ArtsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", null)
                        .WithMany()
                        .HasForeignKey("StreetcodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFTask.Entities.AdditionalContent.Subtitle", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Streetcode")
                        .WithMany("Subtitles")
                        .HasForeignKey("StreetcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.Media.Audio", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Streetcode")
                        .WithOne("Audio")
                        .HasForeignKey("EFTask.Entities.Media.Audio", "StreetcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.Media.Images.Art", b =>
                {
                    b.HasOne("EFTask.Entities.Media.Images.Image", "Image")
                        .WithOne("Art")
                        .HasForeignKey("EFTask.Entities.Media.Images.Art", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("EFTask.Entities.Media.Video", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Streetcode")
                        .WithMany("Videos")
                        .HasForeignKey("StreetcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.Partners.PartnerSourceLink", b =>
                {
                    b.HasOne("EFTask.Entities.Partners.Partner", "Partner")
                        .WithMany("PartnerSourceLinks")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("EFTask.Entities.Partners.StreetcodePartner", b =>
                {
                    b.HasOne("EFTask.Entities.Partners.Partner", "Partner")
                        .WithMany("StreetcodePartners")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Streetcode")
                        .WithMany("StreetcodePartners")
                        .HasForeignKey("StreetcodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.Sources.SourceLink", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Streetcode")
                        .WithMany("SourceLinks")
                        .HasForeignKey("StreetcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.RelatedFigure", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Observer")
                        .WithMany("Observers")
                        .HasForeignKey("ObserverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Target")
                        .WithMany("Targets")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observer");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.TextContent.Fact", b =>
                {
                    b.HasOne("EFTask.Entities.Media.Images.Image", "Image")
                        .WithMany("Facts")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.TextContent.Text", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Streetcode")
                        .WithOne("Text")
                        .HasForeignKey("EFTask.Entities.Streetcode.TextContent.Text", "StreetcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.Transactions.TransactionLink", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Streetcode")
                        .WithOne("TransactionLink")
                        .HasForeignKey("EFTask.Entities.Transactions.TransactionLink", "StreetcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streetcode");
                });

            modelBuilder.Entity("FactStreetcode", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.TextContent.Fact", null)
                        .WithMany()
                        .HasForeignKey("FactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", null)
                        .WithMany()
                        .HasForeignKey("StreetcodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HistoricalContextTimelineItem", b =>
                {
                    b.HasOne("EFTask.Entities.Timeline.HistoricalContext", null)
                        .WithMany()
                        .HasForeignKey("HistoricalContextsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Timeline.TimelineItem", null)
                        .WithMany()
                        .HasForeignKey("TimelineItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImageStreetcode", b =>
                {
                    b.HasOne("EFTask.Entities.Media.Images.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", null)
                        .WithMany()
                        .HasForeignKey("StreetcodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SourceLinkSourceLinkCategory", b =>
                {
                    b.HasOne("EFTask.Entities.Sources.SourceLinkCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Sources.SourceLink", null)
                        .WithMany()
                        .HasForeignKey("SourceLinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreetcodeTag", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", null)
                        .WithMany()
                        .HasForeignKey("StreetcodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.AdditionalContent.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreetcodeTimelineItem", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", null)
                        .WithMany()
                        .HasForeignKey("StreetcodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Timeline.TimelineItem", null)
                        .WithMany()
                        .HasForeignKey("TimelineItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreetcodeToponym", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", null)
                        .WithMany()
                        .HasForeignKey("StreetcodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFTask.Entities.Toponyms.Toponym", null)
                        .WithMany()
                        .HasForeignKey("ToponymsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFTask.Entities.AdditionalContent.Coordinates.StreetcodeCoordinate", b =>
                {
                    b.HasOne("EFTask.Entities.Streetcode.Streetcode", "Streetcode")
                        .WithOne("Coordinate")
                        .HasForeignKey("EFTask.Entities.AdditionalContent.Coordinates.StreetcodeCoordinate", "StreetcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streetcode");
                });

            modelBuilder.Entity("EFTask.Entities.AdditionalContent.Coordinates.ToponymCoordinate", b =>
                {
                    b.HasOne("EFTask.Entities.Toponyms.Toponym", "Toponym")
                        .WithMany("Coordinates")
                        .HasForeignKey("ToponymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Toponym");
                });

            modelBuilder.Entity("EFTask.Entities.Media.Images.Image", b =>
                {
                    b.Navigation("Art");

                    b.Navigation("Facts");
                });

            modelBuilder.Entity("EFTask.Entities.Partners.Partner", b =>
                {
                    b.Navigation("PartnerSourceLinks");

                    b.Navigation("StreetcodePartners");
                });

            modelBuilder.Entity("EFTask.Entities.Streetcode.Streetcode", b =>
                {
                    b.Navigation("Audio");

                    b.Navigation("Coordinate");

                    b.Navigation("Observers");

                    b.Navigation("SourceLinks");

                    b.Navigation("StreetcodePartners");

                    b.Navigation("Subtitles");

                    b.Navigation("Targets");

                    b.Navigation("Text");

                    b.Navigation("TransactionLink");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("EFTask.Entities.Toponyms.Toponym", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
