//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_FailedToValidateSharedResource_uk_UA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_FailedToValidateSharedResource_uk_UA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.SharedResource.FailedToValidateSharedResource.uk-UA", typeof(SharedResource_FailedToValidateSharedResource_uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; не може бути пусте.
        /// </summary>
        internal static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; не може бути пусте, якщо введено поле &apos;{0}&apos;.
        /// </summary>
        internal static string CannotBeEmptyWithCondition {
            get {
                return ResourceManager.GetString("CannotBeEmptyWithCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса електронної пошти повинна бути в правильному форматі.
        /// </summary>
        internal static string EmailAddressFormat {
            get {
                return ResourceManager.GetString("EmailAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; має бути більше ніж {1}.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинка з ідентифікатором {0} не існує.
        /// </summary>
        internal static string ImageDoesntExist {
            get {
                return ResourceManager.GetString("ImageDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; має недійсне значення.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; обов&apos;язкове поле.
        /// </summary>
        internal static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логотип має відповідати посиланню.
        /// </summary>
        internal static string LogoMustMatchUrl {
            get {
                return ResourceManager.GetString("LogoMustMatchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальна довжина поля &apos;{0}&apos; - {1}.
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; має бути між {1} і {2}.
        /// </summary>
        internal static string MustBeBetween {
            get {
                return ResourceManager.GetString("MustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина поля &apos;{0}&apos; має бути від {1} до {2}.
        /// </summary>
        internal static string MustBeInRange {
            get {
                return ResourceManager.GetString("MustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; приймає тільки наступні значення: {1}.
        /// </summary>
        internal static string MustBeOneOf {
            get {
                return ResourceManager.GetString("MustBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; має бути унікальним.
        /// </summary>
        internal static string MustBeUnique {
            get {
                return ResourceManager.GetString("MustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальна довжина {0}.
        /// </summary>
        internal static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок це обовʼязкове поле.
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транслітероване посилання має містити тільки латинські літери, цифри та дефіс.
        /// </summary>
        internal static string TransliterationUrlFormat {
            get {
                return ResourceManager.GetString("TransliterationUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; повинно бути дійсною URL адресою .
        /// </summary>
        internal static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; ({1}) повинно бути дійсною URL адресою .
        /// </summary>
        internal static string ValidUrl_UrlDisplayed {
            get {
                return ResourceManager.GetString("ValidUrl_UrlDisplayed", resourceCulture);
            }
        }
    }
}
