//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_FailedToValidateSharedResource_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_FailedToValidateSharedResource_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Streetcode.BLL.Resources.SharedResource_FailedToValidateSharedResource_en_US", typeof(SharedResource_FailedToValidateSharedResource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        internal static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        internal static string TitleNewsAlreadyExists {
            get {
                return ResourceManager.GetString("TitleNewsAlreadyExists", resourceCulture);
            }
        }
        
        internal static string TextRequired {
            get {
                return ResourceManager.GetString("TextRequired", resourceCulture);
            }
        }
        
        internal static string TextNewsAlreadyExists {
            get {
                return ResourceManager.GetString("TextNewsAlreadyExists", resourceCulture);
            }
        }
        
        internal static string InvalidImageIdValue {
            get {
                return ResourceManager.GetString("InvalidImageIdValue", resourceCulture);
            }
        }
        
        internal static string ImageIdNotExists {
            get {
                return ResourceManager.GetString("ImageIdNotExists", resourceCulture);
            }
        }
        
        internal static string CreationDateRequired {
            get {
                return ResourceManager.GetString("CreationDateRequired", resourceCulture);
            }
        }
        
        internal static string URLRequired {
            get {
                return ResourceManager.GetString("URLRequired", resourceCulture);
            }
        }
        
        internal static string URLInvalid {
            get {
                return ResourceManager.GetString("URLInvalid", resourceCulture);
            }
        }
        
        internal static string URLAlreadyExistsNews {
            get {
                return ResourceManager.GetString("URLAlreadyExistsNews", resourceCulture);
            }
        }
    }
}
