//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_CannotFindSharedResource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_CannotFindSharedResource_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.SharedResource.CannotFindSharedResource.en-US", typeof(SharedResource_CannotFindSharedResource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an art with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnArtWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnArtWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindAnAudioWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindAnAudioWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnAudioWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnAudioWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with the corresponding streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnAudioWithTheCorrespondingStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnAudioWithTheCorrespondingStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an image with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindAnImageWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindAnImageWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an image with the corresponding streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnImageWithTheCorrespondingStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnImageWithTheCorrespondingStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any arts.
        /// </summary>
        internal static string CannotFindAnyArts {
            get {
                return ResourceManager.GetString("CannotFindAnyArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any art with corresponding streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyArtWithCorrespondingStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyArtWithCorrespondingStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any audios.
        /// </summary>
        internal static string CannotFindAnyAudios {
            get {
                return ResourceManager.GetString("CannotFindAnyAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any fact.
        /// </summary>
        internal static string CannotFindAnyFact {
            get {
                return ResourceManager.GetString("CannotFindAnyFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any fact by the streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyFactByTheStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyFactByTheStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any fact with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyFactWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyFactWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any historical contexts.
        /// </summary>
        internal static string CannotFindAnyHistoricalContexts {
            get {
                return ResourceManager.GetString("CannotFindAnyHistoricalContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any image.
        /// </summary>
        internal static string CannotFindAnyImage {
            get {
                return ResourceManager.GetString("CannotFindAnyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partners.
        /// </summary>
        internal static string CannotFindAnyPartners {
            get {
                return ResourceManager.GetString("CannotFindAnyPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partner with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyPartnerWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyPartnerWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any positions.
        /// </summary>
        internal static string CannotFindAnyPositions {
            get {
                return ResourceManager.GetString("CannotFindAnyPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any field with this name.
        /// </summary>
        internal static string CannotFindAnyPropertyWithThisName {
            get {
                return ResourceManager.GetString("CannotFindAnyPropertyWithThisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any related figures by a streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyRelatedFiguresByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyRelatedFiguresByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any source category with the streetcode id {0}.
        /// </summary>
        internal static string CannotFindAnySourceCategoryWithTheStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnySourceCategoryWithTheStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any srcCategory by the corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnySrcCategoryByTheCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnySrcCategoryByTheCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyStreetcodeWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyStreetcodeWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding index: {0}.
        /// </summary>
        internal static string CannotFindAnyStreetcodeWithCorrespondingIndex {
            get {
                return ResourceManager.GetString("CannotFindAnyStreetcodeWithCorrespondingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyStreetcodeWithCorrespondingStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyStreetcodeWithCorrespondingStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding tagid: {0}.
        /// </summary>
        internal static string CannotFindAnyStreetcodeWithCorrespondingTagId {
            get {
                return ResourceManager.GetString("CannotFindAnyStreetcodeWithCorrespondingTagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any subtitle by the streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnySubtitleByTheStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnySubtitleByTheStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any subtitles.
        /// </summary>
        internal static string CannotFindAnySubtitles {
            get {
                return ResourceManager.GetString("CannotFindAnySubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tag by the streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyTagByTheStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyTagByTheStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tag by the title: {0}.
        /// </summary>
        internal static string CannotFindAnyTagByTheTitle {
            get {
                return ResourceManager.GetString("CannotFindAnyTagByTheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tags.
        /// </summary>
        internal static string CannotFindAnyTags {
            get {
                return ResourceManager.GetString("CannotFindAnyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team.
        /// </summary>
        internal static string CannotFindAnyTeam {
            get {
                return ResourceManager.GetString("CannotFindAnyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team links.
        /// </summary>
        internal static string CannotFindAnyTeamLinks {
            get {
                return ResourceManager.GetString("CannotFindAnyTeamLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyTeamWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyTeamWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any term.
        /// </summary>
        internal static string CannotFindAnyTerm {
            get {
                return ResourceManager.GetString("CannotFindAnyTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any term with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyTermWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyTermWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any text.
        /// </summary>
        internal static string CannotFindAnyText {
            get {
                return ResourceManager.GetString("CannotFindAnyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any text with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyTextWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyTextWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any timelineItem.
        /// </summary>
        internal static string CannotFindAnyTimelineItem {
            get {
                return ResourceManager.GetString("CannotFindAnyTimelineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any timeline item by the streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyTimelineItemByTheStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyTimelineItemByTheStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any toponym by the streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyToponymByTheStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyToponymByTheStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any toponym with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyToponymWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyToponymWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any transaction link.
        /// </summary>
        internal static string CannotFindAnyTransactionLink {
            get {
                return ResourceManager.GetString("CannotFindAnyTransactionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any transaction link with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyTransactionLinkWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyTransactionLinkWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any video by the streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyVideoByTheStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyVideoByTheStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any videos.
        /// </summary>
        internal static string CannotFindAnyVideos {
            get {
                return ResourceManager.GetString("CannotFindAnyVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a category with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindCategoryWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindCategoryWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find coordinates by streetcodeId: {0}.
        /// </summary>
        internal static string CannotFindCoordinatesByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindCoordinatesByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find coordinate with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindCoordinateWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindCoordinateWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a fact with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindFactWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindFactWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find historical context with id {0}.
        /// </summary>
        internal static string CannotFindHistoricalContextWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindHistoricalContextWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find historical context with title &apos;{0}&apos;.
        /// </summary>
        internal static string CannotFindHistoricalContextWithTitle {
            get {
                return ResourceManager.GetString("CannotFindHistoricalContextWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an image with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindImageWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindImageWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a job with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindJobWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindJobWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a partners by a streetcode id: {0}.
        /// </summary>
        internal static string CannotFindPartnersByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindPartnersByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a position with id {0}.
        /// </summary>
        internal static string CannotFindPositionWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindPositionWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a position with title &apos;{0}&apos;.
        /// </summary>
        internal static string CannotFindPositionWithCorrespondingTitle {
            get {
                return ResourceManager.GetString("CannotFindPositionWithCorrespondingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find record for qrId.
        /// </summary>
        internal static string CannotFindRecordWithQrId {
            get {
                return ResourceManager.GetString("CannotFindRecordWithQrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find record for streetcode with id {0}.
        /// </summary>
        internal static string CannotFindRecordWithStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindRecordWithStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a related term with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindRelatedTermWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindRelatedTermWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a relation between streetcodes with corresponding ids: {0} &amp; {1}.
        /// </summary>
        internal static string CannotFindRelationBetweenStreetcodesWithCorrespondingIds {
            get {
                return ResourceManager.GetString("CannotFindRelationBetweenStreetcodesWithCorrespondingIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by id.
        /// </summary>
        internal static string CannotFindStreetcodeById {
            get {
                return ResourceManager.GetString("CannotFindStreetcodeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by transliteration url: {0}.
        /// </summary>
        internal static string CannotFindStreetcodeByTransliterationUrl {
            get {
                return ResourceManager.GetString("CannotFindStreetcodeByTransliterationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a streetcode with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindStreetcodeWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindStreetcodeWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a subtitle with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindSubtitleWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindSubtitleWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a Tag with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindTagWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindTagWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a text with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindTextWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindTextWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a timeline item with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindTimelineItemWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindTimelineItemWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a transaction link by a streetcode id: {0}.
        /// </summary>
        internal static string CannotFindTransactionLinkByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindTransactionLinkByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a transaction link by a streetcode id: {0}, because such streetcode doesn`t exist.
        /// </summary>
        internal static string CannotFindTransactionLinkByStreetcodeIdBecause {
            get {
                return ResourceManager.GetString("CannotFindTransactionLinkByStreetcodeIdBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a video with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindVideoWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindVideoWithCorrespondingId", resourceCulture);
            }
        }
    }
}
