//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_FailedToValidateSharedResource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_FailedToValidateSharedResource_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.SharedResource.FailedToValidateSharedResource.en-US", typeof(SharedResource_FailedToValidateSharedResource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; cannot be empty.
        /// </summary>
        internal static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; cannot be empty if field &apos;{1}&apos; is provided.
        /// </summary>
        internal static string CannotBeEmptyWithCondition {
            get {
                return ResourceManager.GetString("CannotBeEmptyWithCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Date String&apos; accepts only cyrillic letters, numbers, dashes (–) and parentheses..
        /// </summary>
        internal static string DateStringFormat {
            get {
                return ResourceManager.GetString("DateStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address must be in the correct format.
        /// </summary>
        internal static string EmailAddressFormat {
            get {
                return ResourceManager.GetString("EmailAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streetcode of type &apos;Event&apos; cannot has &apos;First name&apos; and &apos;Last name&apos;.
        /// </summary>
        internal static string EventStreetcodeCannotHasFirstName {
            get {
                return ResourceManager.GetString("EventStreetcodeCannotHasFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be greater than {1}.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image with id {0} doesnt exist.
        /// </summary>
        internal static string ImageDoesntExist {
            get {
                return ResourceManager.GetString("ImageDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image size can&apos;t exceed {0} MB.
        /// </summary>
        internal static string ImageSizeExceeded {
            get {
                return ResourceManager.GetString("ImageSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;Url&apos; accepts only small latin alphabet letters, hyphen and numbers..
        /// </summary>
        internal static string InvalidNewsUrl {
            get {
                return ResourceManager.GetString("InvalidNewsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; has invalid precision.
        /// </summary>
        internal static string InvalidPrecision {
            get {
                return ResourceManager.GetString("InvalidPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is required.
        /// </summary>
        internal static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the field &apos;{0}&apos; must be from {1} to {2}.
        /// </summary>
        internal static string LengthMustBeInRange {
            get {
                return ResourceManager.GetString("LengthMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link does not match the selected social network.
        /// </summary>
        internal static string LogoMustMatchUrl {
            get {
                return ResourceManager.GetString("LogoMustMatchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of field &apos;{0}&apos; is {1}.
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must be between {1} and {2}.
        /// </summary>
        internal static string MustBeBetween {
            get {
                return ResourceManager.GetString("MustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; accepts only following values: {1}.
        /// </summary>
        internal static string MustBeOneOf {
            get {
                return ResourceManager.GetString("MustBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must be unique.
        /// </summary>
        internal static string MustBeUnique {
            get {
                return ResourceManager.GetString("MustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; may contain at most one colored image..
        /// </summary>
        internal static string MustContainAtMostOneAlt0 {
            get {
                return ResourceManager.GetString("MustContainAtMostOneAlt0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; may contain at most one image for links..
        /// </summary>
        internal static string MustContainAtMostOneAlt2 {
            get {
                return ResourceManager.GetString("MustContainAtMostOneAlt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must contain exactly one black and white image..
        /// </summary>
        internal static string MustContainExactlyOneAlt1 {
            get {
                return ResourceManager.GetString("MustContainExactlyOneAlt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be in the past..
        /// </summary>
        internal static string MustNotBeInPast {
            get {
                return ResourceManager.GetString("MustNotBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliteration url must consists of small latin characters, numbers and hyphen.
        /// </summary>
        internal static string TransliterationUrlFormat {
            get {
                return ResourceManager.GetString("TransliterationUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must be valid url.
        /// </summary>
        internal static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; ({1}) must be valid url.
        /// </summary>
        internal static string ValidUrl_UrlDisplayed {
            get {
                return ResourceManager.GetString("ValidUrl_UrlDisplayed", resourceCulture);
            }
        }
    }
}
